# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-17 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pojName',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
